- name: Restart Microservice
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Create a file
      shell: echo $(date) " - Testing Auto Remediation" > /var/lib/awx/projects/AIOPS/AutoRemediation.txt
      args:
        creates: "/var/lib/awx/projects/AIOPS/AutoRemediation.txt"
